"""add scheduled_messages table

Revision ID: 06b730e78a80
Revises: 9f42e2f51be1
Create Date: 2026-06-23 12:20:10.554053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b730e78a80'
down_revision = '9f42e2f51be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_person_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deliver_on', sa.Date(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['recipient_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_messages_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_deliver_on'), ['deliver_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_recipient_person_id'), ['recipient_person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_recipient_person_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_family_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_deliver_on'))
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_author_user_id'))

    op.drop_table('scheduled_messages')
    # ### end Alembic commands ###
