"""Add quantity to meal items, category and due_date to assignments

Revision ID: 0bcccbc098a7
Revises: e41b9bccad42
Create Date: 2026-05-16 14:59:45.512274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcccbc098a7'
down_revision = 'e41b9bccad42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    with op.batch_alter_table('event_meal_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_meal_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
