"""Add assigned family to event meal

Revision ID: 149dda51e206
Revises: a00ca4c8615c
Create Date: 2026-05-12 20:05:36.213590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149dda51e206'
down_revision = 'a00ca4c8615c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_family_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_event_meals_assigned_family', 'people', ['assigned_family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_meals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_meals_assigned_family', type_='foreignkey')
        batch_op.drop_column('assigned_family_id')

    # ### end Alembic commands ###
