"""add event payment config and records

Revision ID: 18485f9a33a7
Revises: cdf7968e86fb
Create Date: 2026-06-05 17:02:56.019302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18485f9a33a7'
down_revision = 'cdf7968e86fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_payment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('charge_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('event_payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('payer_user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'payer_user_id')
    )
    with op.batch_alter_table('event_payment_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_payment_records_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_payment_records_payer_user_id'), ['payer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_payment_records_stripe_checkout_session_id'), ['stripe_checkout_session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_payment_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_payment_records_stripe_checkout_session_id'))
        batch_op.drop_index(batch_op.f('ix_event_payment_records_payer_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_payment_records_event_id'))

    op.drop_table('event_payment_records')
    op.drop_table('event_payment_configs')
    # ### end Alembic commands ###
