"""add photo thumb_path

Revision ID: 293db9865a3c
Revises: 3d3f8d534913
Create Date: 2026-06-12 14:09:19.494819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293db9865a3c'
down_revision = '3d3f8d534913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('thumb_path')

    # ### end Alembic commands ###
