"""add recur_freq and recur_until to events

Revision ID: 32336809d7ce
Revises: e549158e0b3f
Create Date: 2026-06-09 15:03:48.181049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32336809d7ce'
down_revision = 'e549158e0b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recur_freq', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recur_until', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('recur_until')
        batch_op.drop_column('recur_freq')

    # ### end Alembic commands ###
