"""add assignment_tasks table

Revision ID: 3a2ef4f55d0e
Revises: 5636c73c88c2
Create Date: 2026-06-09 14:38:40.987626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2ef4f55d0e'
down_revision = '5636c73c88c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['event_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_tasks_assignment_id'), ['assignment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_tasks_assignment_id'))

    op.drop_table('assignment_tasks')
    # ### end Alembic commands ###
