"""family feature flags and default event location

Revision ID: 49c90d5a07d5
Revises: 8c3fc56eb16b
Create Date: 2026-06-07 15:06:57.709039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c90d5a07d5'
down_revision = '8c3fc56eb16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_member_approval', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('default_event_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('enable_polls', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('enable_greeting_cards', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_column('enable_greeting_cards')
        batch_op.drop_column('enable_polls')
        batch_op.drop_column('default_event_location')
        batch_op.drop_column('require_member_approval')

    # ### end Alembic commands ###
