"""Add lgbtq options and pronouns

Revision ID: 4a5d5ff1b945
Revises: ed18e8e094bb
Create Date: 2026-05-16 12:38:34.651836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5d5ff1b945'
down_revision = 'ed18e8e094bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_lgbtq_options', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('pronouns')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_column('has_lgbtq_options')

    # ### end Alembic commands ###
