"""Add photo_position to person

Revision ID: 513544d117cf
Revises: 149dda51e206
Create Date: 2026-05-13 21:13:03.732375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513544d117cf'
down_revision = '149dda51e206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_position', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('photo_position')

    # ### end Alembic commands ###
