"""initial schema

Revision ID: 528abe8da32b
Revises: 
Create Date: 2026-05-08 20:46:14.496217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528abe8da32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('birthplace', sa.String(length=100), nullable=True),
    sa.Column('maiden_name', sa.String(length=100), nullable=True),
    sa.Column('deathday', sa.Date(), nullable=True),
    sa.Column('deathplace', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_child',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('spouse_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person1_id', sa.Integer(), nullable=False),
    sa.Column('person2_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('marriage_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=100), nullable=True),
    sa.Column('confirmation_token_expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person1_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['person2_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('verification_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_delegate', sa.Boolean(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('invitation_token', sa.String(length=100), nullable=True),
    sa.Column('invitation_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('spouse_relationships')
    op.drop_table('parent_child')
    op.drop_table('people')
    # ### end Alembic commands ###
