"""add system_config table

Revision ID: 62948a3f893c
Revises: c77b1a404ae1
Create Date: 2026-06-06 19:25:38.338740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62948a3f893c'
down_revision = 'c77b1a404ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
