"""Replace parent_child junction with ParentRelationship model

Revision ID: 65aad2121dea
Revises: 513544d117cf
Create Date: 2026-05-13 21:52:19.239436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65aad2121dea'
down_revision = '513544d117cf'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('parent_relationships',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # Migrate existing rows with default role
    conn = op.get_bind()
    rows = conn.execute(sa.text('SELECT parent_id, child_id FROM parent_child')).fetchall()
    for row in rows:
        conn.execute(sa.text(
            "INSERT OR IGNORE INTO parent_relationships (parent_id, child_id, role) VALUES (:p, :c, 'parent')"
        ), {'p': row[0], 'c': row[1]})
    op.drop_table('parent_child')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_child',
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.drop_table('parent_relationships')
    # ### end Alembic commands ###
