"""add family payout accounts and payment record net fields

Revision ID: 736fc8c87c0b
Revises: 18485f9a33a7
Create Date: 2026-06-05 17:20:14.007679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736fc8c87c0b'
down_revision = '18485f9a33a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_payout_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=100), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id')
    )
    with op.batch_alter_table('event_payment_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_transfer_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payout_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('event_payment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_payment_records_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_payment_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_payment_records_stripe_payment_intent_id'))
        batch_op.drop_column('stripe_payment_intent_id')
        batch_op.drop_column('net_cents')

    with op.batch_alter_table('event_payment_configs', schema=None) as batch_op:
        batch_op.drop_column('payout_at')
        batch_op.drop_column('payout_transfer_id')

    op.drop_table('family_payout_accounts')
    # ### end Alembic commands ###
