"""add event time and geo fields

Revision ID: 741bbc29bc96
Revises: 736fc8c87c0b
Create Date: 2026-06-05 23:43:20.102944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741bbc29bc96'
down_revision = '736fc8c87c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
