"""add spot_type to sleeping spots

Revision ID: 758e6094300c
Revises: 98e108ab94f6
Create Date: 2026-06-06 00:43:57.131607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758e6094300c'
down_revision = '98e108ab94f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_sleeping_spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_sleeping_spots', schema=None) as batch_op:
        batch_op.drop_column('spot_type')

    # ### end Alembic commands ###
