"""add family_cap_cents to event_payment_configs

Revision ID: 98e108ab94f6
Revises: 741bbc29bc96
Create Date: 2026-06-06 00:37:20.990646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e108ab94f6'
down_revision = '741bbc29bc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_payment_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_cap_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_payment_configs', schema=None) as batch_op:
        batch_op.drop_column('family_cap_cents')

    # ### end Alembic commands ###
