"""add family stories

Revision ID: 9f42e2f51be1
Revises: ae70de91ca89
Create Date: 2026-06-13 20:12:40.457607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f42e2f51be1'
down_revision = 'ae70de91ca89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_prompts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_prompts_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_prompts_person_id'), ['person_id'], unique=False)

    op.create_table('story_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['story_prompts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id')
    )
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_stories', sa.Boolean(), server_default='true', nullable=False))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stories_enabled', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('story_last_prompted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('story_last_prompted_at')
        batch_op.drop_column('stories_enabled')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_column('enable_stories')

    op.drop_table('story_responses')
    with op.batch_alter_table('story_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_prompts_person_id'))
        batch_op.drop_index(batch_op.f('ix_story_prompts_family_id'))
        batch_op.drop_index(batch_op.f('ix_story_prompts_created_at'))

    op.drop_table('story_prompts')
    # ### end Alembic commands ###
