"""add event agenda items table and has_agenda flag

Revision ID: 9f468e4961f3
Revises: c5a9f1e3b2d7
Create Date: 2026-06-25 19:06:13.959928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f468e4961f3'
down_revision = 'c5a9f1e3b2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('item_date', sa.Date(), nullable=True),
    sa.Column('item_time', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_agenda_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_agenda_items_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_agenda', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('has_agenda')

    with op.batch_alter_table('event_agenda_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_agenda_items_event_id'))

    op.drop_table('event_agenda_items')
    # ### end Alembic commands ###
