"""Replace meal signups with meal items

Revision ID: a00ca4c8615c
Revises: 56fccccd06b8
Create Date: 2026-05-12 20:01:35.227701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00ca4c8615c'
down_revision = '56fccccd06b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('is_cleanup', sa.Boolean(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['event_meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event_meal_signups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_meal_signups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.Column('person_id', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['event_meals.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event_meal_items')
    # ### end Alembic commands ###
