"""Add account_id, plan, stripe_customer_id to families

Revision ID: b6862d371e96
Revises: 71c300756fdf
Create Date: 2026-05-20 20:19:56.705715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6862d371e96'
down_revision = '71c300756fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_families_account_id'), ['account_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_families_account_id'))
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('plan')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
