"""payer_user_id nullable for account deletion

Revision ID: b91f9131084d
Revises: 293db9865a3c
Create Date: 2026-06-12 14:15:36.581613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91f9131084d'
down_revision = '293db9865a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_payment_records', schema=None) as batch_op:
        batch_op.alter_column('payer_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_payment_records', schema=None) as batch_op:
        batch_op.alter_column('payer_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
