"""add support_notes table

Revision ID: c53e85e780df
Revises: 1a25e3f6a332
Create Date: 2026-05-26 16:59:52.795391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53e85e780df'
down_revision = '1a25e3f6a332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pod_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_notes_pod_id'), ['pod_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_notes_pod_id'))

    op.drop_table('support_notes')
    # ### end Alembic commands ###
