"""add locations table and event location_id

Revision ID: c77b1a404ae1
Revises: f4e8c2a7b931
Create Date: 2026-06-06 19:00:36.708147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77b1a404ae1'
down_revision = 'f4e8c2a7b931'
branch_labels = None
depends_on = None


def upgrade():
    from alembic import op as _op
    from sqlalchemy import inspect
    bind = op.get_bind()
    insp = inspect(bind)

    if 'locations' not in insp.get_table_names():
        op.create_table('locations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('family_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('address', sa.String(length=200), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    existing_idx = [i['name'] for i in insp.get_indexes('locations')]
    if 'ix_locations_family_id' not in existing_idx:
        with op.batch_alter_table('locations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_locations_family_id'), ['family_id'], unique=False)

    event_cols = [c['name'] for c in insp.get_columns('events')]
    if 'location_id' not in event_cols:
        with op.batch_alter_table('events', schema=None) as batch_op:
            batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_events_location_id', 'locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_location_id', type_='foreignkey')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_family_id'))

    op.drop_table('locations')
    # ### end Alembic commands ###
