"""add api_token_blocklist table

Revision ID: d3bb88a89449
Revises: 98326124f892
Create Date: 2026-05-26 18:07:41.371358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bb88a89449'
down_revision = '98326124f892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_blocklist_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_blocklist_jti'))

    op.drop_table('api_token_blocklist')
    # ### end Alembic commands ###
