"""Add email sequence tracking to families

Revision ID: e054946c6c46
Revises: 1b09e1d3a28e
Create Date: 2026-05-23 00:02:43.764033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e054946c6c46'
down_revision = '1b09e1d3a28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_nudge3_sent', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('email_nudge7_sent', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('email_trial_warning_sent', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('email_trial_ended_sent', sa.Boolean(), server_default='0', nullable=False))

    # Mark all pre-existing families as already sent so they aren't spammed on first cron run
    op.execute("UPDATE families SET email_nudge3_sent=1, email_nudge7_sent=1, email_trial_warning_sent=1, email_trial_ended_sent=1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_column('email_trial_ended_sent')
        batch_op.drop_column('email_trial_warning_sent')
        batch_op.drop_column('email_nudge7_sent')
        batch_op.drop_column('email_nudge3_sent')

    # ### end Alembic commands ###
