"""add departure_from and passenger_of_id to carpool_offers

Revision ID: e07a4f070985
Revises: 758e6094300c
Create Date: 2026-06-06 00:50:37.808847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07a4f070985'
down_revision = '758e6094300c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carpool_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_from', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('passenger_of_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_carpool_passenger_of', 'carpool_offers', ['passenger_of_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carpool_offers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_carpool_passenger_of', type_='foreignkey')
        batch_op.drop_column('passenger_of_id')
        batch_op.drop_column('departure_from')

    # ### end Alembic commands ###
