"""Add spouse role fields

Revision ID: ed18e8e094bb
Revises: b10ddce96617
Create Date: 2026-05-15 16:42:53.456522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed18e8e094bb'
down_revision = 'b10ddce96617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spouse_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_for_person1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('role_for_person2', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spouse_relationships', schema=None) as batch_op:
        batch_op.drop_column('role_for_person2')
        batch_op.drop_column('role_for_person1')

    # ### end Alembic commands ###
