"""add location_sleeping_spots table

Revision ID: f866e0a07bb1
Revises: 9b100caa0765
Create Date: 2026-06-07 15:19:24.039446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f866e0a07bb1'
down_revision = '9b100caa0765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_sleeping_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('spot_type', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_sleeping_spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_sleeping_spots_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_sleeping_spots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_sleeping_spots_location_id'))

    op.drop_table('location_sleeping_spots')
    # ### end Alembic commands ###
