"""Add event kind, rsvp_deadline, is_annual

Revision ID: f95db89b1c87
Revises: 3c406743850e
Create Date: 2026-05-23 19:48:03.935303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95db89b1c87'
down_revision = '3c406743850e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rsvp_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_annual', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('is_annual')
        batch_op.drop_column('rsvp_deadline')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
